# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.peach.com:
    container_name: orderer.peach.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      # - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/peach.com/orderers/orderer.peach.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/peach.com/orderers/orderer.peach.com/tls/:/var/hyperledger/orderer/tls
    - orderer.peach.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
###
  peer0.org1.peach.com:
    container_name: peer0.org1.peach.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.peach.com
      - CORE_PEER_ADDRESS=peer0.org1.peach.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.peach.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.peach.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.peach.com/peers/peer0.org1.peach.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.peach.com/peers/peer0.org1.peach.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.peach.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.org1.peach.com:
    container_name: peer1.org1.peach.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.peach.com
      - CORE_PEER_ADDRESS=peer1.org1.peach.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.peach.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.peach.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.peach.com/peers/peer1.org1.peach.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.peach.com/peers/peer1.org1.peach.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org1.peach.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053
###
  peer0.org2.peach.com:
    container_name: peer0.org2.peach.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.peach.com
      - CORE_PEER_ADDRESS=peer0.org2.peach.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.peach.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.peach.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.peach.com/peers/peer0.org2.peach.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.peach.com/peers/peer0.org2.peach.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.peach.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.org2.peach.com:
    container_name: peer1.org2.peach.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.peach.com
      - CORE_PEER_ADDRESS=peer1.org2.peach.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.peach.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.peach.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.peach.com/peers/peer1.org2.peach.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.peach.com/peers/peer1.org2.peach.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org2.peach.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053
###
  peer0.org3.peach.com:
    container_name: peer0.org3.peach.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org3.peach.com
      - CORE_PEER_ADDRESS=peer0.org3.peach.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.peach.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org3.peach.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org3.peach.com/peers/peer0.org3.peach.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org3.peach.com/peers/peer0.org3.peach.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org3.peach.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053

  peer1.org3.peach.com:
    container_name: peer1.org3.peach.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org3.peach.com
      - CORE_PEER_ADDRESS=peer1.org3.peach.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.peach.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.peach.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org3.peach.com/peers/peer1.org3.peach.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org3.peach.com/peers/peer1.org3.peach.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org3.peach.com:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053
###
  peer0.org4.peach.com:
    container_name: peer0.org4.peach.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org4.peach.com
      - CORE_PEER_ADDRESS=peer0.org4.peach.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org4.peach.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org4.peach.com:7051
      - CORE_PEER_LOCALMSPID=Org4MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org4.peach.com/peers/peer0.org4.peach.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org4.peach.com/peers/peer0.org4.peach.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org4.peach.com:/var/hyperledger/production
    ports:
      - 13051:7051
      - 13053:7053

  peer1.org4.peach.com:
    container_name: peer1.org4.peach.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org4.peach.com
      - CORE_PEER_ADDRESS=peer1.org4.peach.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org4.peach.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org4.peach.com:7051
      - CORE_PEER_LOCALMSPID=Org4MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org4.peach.com/peers/peer1.org4.peach.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org4.peach.com/peers/peer1.org4.peach.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org4.peach.com:/var/hyperledger/production
    ports:
      - 14051:7051
      - 14053:7053
###
  peer0.org5.peach.com:
    container_name: peer0.org5.peach.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org5.peach.com
      - CORE_PEER_ADDRESS=peer0.org5.peach.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org5.peach.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org5.peach.com:7051
      - CORE_PEER_LOCALMSPID=Org5MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org5.peach.com/peers/peer0.org5.peach.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org5.peach.com/peers/peer0.org5.peach.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org5.peach.com:/var/hyperledger/production
    ports:
      - 15051:7051
      - 15053:7053

  peer1.org5.peach.com:
    container_name: peer1.org5.peach.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org5.peach.com
      - CORE_PEER_ADDRESS=peer1.org5.peach.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org5.peach.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org5.peach.com:7051
      - CORE_PEER_LOCALMSPID=Org5MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org5.peach.com/peers/peer1.org5.peach.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org5.peach.com/peers/peer1.org5.peach.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org5.peach.com:/var/hyperledger/production
    ports:
      - 16051:7051
      - 16053:7053
###
  peer0.org6.peach.com:
    container_name: peer0.org6.peach.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org6.peach.com
      - CORE_PEER_ADDRESS=peer0.org6.peach.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org6.peach.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org6.peach.com:7051
      - CORE_PEER_LOCALMSPID=Org6MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org6.peach.com/peers/peer0.org6.peach.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org6.peach.com/peers/peer0.org6.peach.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org6.peach.com:/var/hyperledger/production
    ports:
      - 1751:7051
      - 17053:7053

  peer1.org6.peach.com:
    container_name: peer1.org6.peach.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org6.peach.com
      - CORE_PEER_ADDRESS=peer1.org6.peach.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org6.peach.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org6.peach.com:7051
      - CORE_PEER_LOCALMSPID=Org6MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org6.peach.com/peers/peer1.org6.peach.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org6.peach.com/peers/peer1.org6.peach.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org6.peach.com:/var/hyperledger/production
    ports:
      - 18051:7051
      - 18053:7053
###
  peer0.org7.peach.com:
    container_name: peer0.org7.peach.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org7.peach.com
      - CORE_PEER_ADDRESS=peer0.org7.peach.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org7.peach.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org7.peach.com:7051
      - CORE_PEER_LOCALMSPID=Org7MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org7.peach.com/peers/peer0.org7.peach.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org7.peach.com/peers/peer0.org7.peach.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org7.peach.com:/var/hyperledger/production
    ports:
      - 19051:7051
      - 19053:7053

  peer1.org7.peach.com:
    container_name: peer1.org7.peach.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org7.peach.com
      - CORE_PEER_ADDRESS=peer1.org7.peach.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org7.peach.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org7.peach.com:7051
      - CORE_PEER_LOCALMSPID=Org7MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org7.peach.com/peers/peer1.org7.peach.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org7.peach.com/peers/peer1.org7.peach.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org7.peach.com:/var/hyperledger/production
    ports:
      - 20051:7051
      - 20053:7053
