# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.peach.com:

  peer0.org1.peach.com:
  peer1.org1.peach.com:

  peer0.org2.peach.com:
  peer1.org2.peach.com:

  peer0.org3.peach.com:
  peer1.org3.peach.com:

  peer0.org4.peach.com:
  peer1.org4.peach.com:

  peer0.org5.peach.com:
  peer1.org5.peach.com:

  peer0.org6.peach.com:
  peer1.org6.peach.com:

  peer0.org7.peach.com:
  peer1.org7.peach.com:

networks:
  byfn:

services:
  ca.org1.peach.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.peach.com
      # - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.peach.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/11377b2c853e683544f53f0d953a27074c3ebcc76aaaa18910195b2668088609_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org1.peach.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org1.peach.com
    networks:
      - byfn

  ca.org2.peach.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org2.peach.com
      # - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.peach.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a5c7c7d37f875d0cb9809bd29bc24c55eb939c4273888260772ef88703e284ab_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org2.peach.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org2.peach.com
    networks:
      - byfn

  ca.org3.peach.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org3.peach.com
      # - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.peach.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a9518a62e242b2f4aa98187cd55d43a9bb58290161f742c874a3c3282b44ca44_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org3.peach.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org3.peach.com
    networks:
      - byfn

  ca.org4.peach.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org4.peach.com
      # - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org4.peach.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a4e7fe9b02c96fd25dd3705263b94573865fa066f034b8ba076df6415767025d_sk
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org4.peach.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org4.peach.com
    networks:
      - byfn

  ca.org5.peach.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org5.peach.com
      # - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org5.peach.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/9bb51e7d82058fea0f2a4264ec97c9f1d80a5631a00259924caafa182bbd1ba3_sk
    ports:
      - "11054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org5.peach.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org5.peach.com
    networks:
      - byfn

  ca.org6.peach.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org6.peach.com
      # - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org6.peach.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/42f69536e611bd7a7aabf8a0864136176edf89e4aac61d4165c717b2cb39b371_sk
    ports:
      - "12054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org6.peach.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org6.peach.com
    networks:
      - byfn

  ca.org7.peach.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org7.peach.com
      # - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org7.peach.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/2f2741266dd34f751c23deb870084388800bbb03c79e4b43dd71965e620c89ea_sk
    ports:
      - "13054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org7.peach.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org7.peach.com
    networks:
      - byfn

  orderer.peach.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.peach.com
    container_name: orderer.peach.com
    networks:
      - byfn

  peer0.org1.peach.com:
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.peach.com
    networks:
      - byfn

  peer1.org1.peach.com:
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.peach.com
    networks:
      - byfn

  peer0.org2.peach.com:
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.peach.com
    networks:
      - byfn

  peer1.org2.peach.com:
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.peach.com
    networks:
      - byfn

  peer0.org3.peach.com:
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org3.peach.com
    networks:
      - byfn

  peer1.org3.peach.com:
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org3.peach.com
    networks:
      - byfn

  peer0.org4.peach.com:
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org4.peach.com
    networks:
      - byfn

  peer1.org4.peach.com:
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org4.peach.com
    networks:
      - byfn

  peer0.org5.peach.com:
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org5.peach.com
    networks:
      - byfn

  peer1.org5.peach.com:
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org5.peach.com
    networks:
      - byfn

  peer0.org6.peach.com:
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org6.peach.com
    networks:
      - byfn

  peer1.org6.peach.com:
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org6.peach.com
    networks:
      - byfn

  peer0.org7.peach.com:
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org7.peach.com
    networks:
      - byfn

  peer1.org7.peach.com:
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org7.peach.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.peach.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      # - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.peach.com/peers/peer0.org1.peach.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.peach.com/peers/peer0.org1.peach.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.peach.com/peers/peer0.org1.peach.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.peach.com/users/Admin@org1.peach.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.peach.com
      - peer0.org1.peach.com
      - peer1.org1.peach.com
      - peer0.org2.peach.com
      - peer1.org2.peach.com
      - peer0.org3.peach.com
      - peer1.org3.peach.com
      - peer0.org4.peach.com
      - peer1.org4.peach.com
      - peer0.org5.peach.com
      - peer1.org5.peach.com
      - peer0.org6.peach.com
      - peer1.org6.peach.com
      - peer0.org7.peach.com
      - peer1.org7.peach.com
    networks:
      - byfn
